name: Deploy to Existing Environment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy, ex v1.4'
        required: true
        type: string
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
        default: 'dev'

permissions:
  contents: write
  actions: read

jobs:
  deploy:
    runs-on: ${{ inputs.environment == 'prod' && 'prod-vspec-lib' || inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: "3.11"

      - name: Create Relese Files
        run: |
          python3 -m venv ./.venv
          source ./.venv/bin/activate
          pip install -e .
          ./release.sh ${{ inputs.version }}

      - name: Run library Deploy
        uses: Veridise/release_helpers/.github/actions/library-release-action/deploy@main
        with:
            environment: ${{ inputs.environment }}
            bucket_name: "${{ inputs.environment }}-oregon-main-audithub"
            bucket_path: vspeclib
            version: ${{ inputs.version }}
